### ISSUE TITLE
(noob question) I'm wondering how to specify tcp connections for minecraft server or http for local dev apps?

### ISSUE THREAD

**Issue by richard523** [cmars/onionpipe#118]
I'm thinking this would have to be some cmd line flag such as ngrok's version:

```
ngrok http 8080
```

or in the case of my Minecraft server....

```
ngrok tcp 25565
```

**Comment by cmars** [comment]
onionpipe isn't designed to be ngrok compatible. It can sort-of function like ngrok, but keep in mind that onionpipe routes traffic over the Tor network as hidden services. This doesn't depend on centralized hosting or a SaaS (like ngrok) but it does mean that your network performance will be determined by that of the Tor network.

This may or may not be acceptable for your use case.

The README has some example commands. For a persistent onion address, you could do something like this:

```
onionpipe 8000~80@minecraft 25565@minecraft
```

Which will use (or create) a persistent onion address with a private key named "minecraft". Local port 8000 will be mapped to <onion address>:80, and local port 25565 will be exposed on the same port <onion address>:25565.

You'll have to read the log output to get the onion address, like this:

```
⬢ [c@toolbox onionpipe]$ ./onionpipe 8000~80@minecraft 25565@minecraft
2024/12/19 11:08:34 starting tor...
127.0.0.1:8000 => hp64zg2kegxjr6xinw4ofs7kb2kdv25qw2zfoxgosf44ipgw5nqqzlqd.onion:80
127.0.0.1:25565 => hp64zg2kegxjr6xinw4ofs7kb2kdv25qw2zfoxgosf44ipgw5nqqzlqd.onion:25565

press Ctrl-C to exit
```

Once you've run the above, you can view or administer the "minecraft" hidden service with `onionpipe service` subcommands, like this:

```
⬢ [c@toolbox onionpipe]$ ./onionpipe service list
{
  "minecraft": {
    "address": "hp64zg2kegxjr6xinw4ofs7kb2kdv25qw2zfoxgosf44ipgw5nqq"
  }
}
```

Now, to actually connect to that minecraft server from another host, on that other machine, the player would need to either have a minecraft client that is capable of connecting to Tor (unlikely), or they'd need to route your minecraft server to a local port, like this:

```
onionpipe hp64zg2kegxjr6xinw4ofs7kb2kdv25qw2zfoxgosf44ipgw5nqqzlqd.onion:25565
```

That will open a local port to the minecraft server on localhost:25565, which a vanilla minecraft client could then connect to.
