### ISSUE TITLE
can't write to docker volume / persistence of secrets.yaml

### ISSUE THREAD

**Issue by watercrossing** [cmars/onionpipe#25]
A simple `docker run onionpipe:latest 172.17.0.1:80~80@test` fails with ``mkdir /.local: permission denied` because onionpipe will try to save the secrets.yaml file to `/.local/share/onionpipe/secrets.yaml`:
https://github.com/cmars/onionpipe/blob/804fcbbcc08e62b6d512c26f6dfebdb435ac8fac/app/app.go#L45
This is because `$HOME` is `/` for the non-existing user 1000 inside docker.

I think the best fix here is to create a user inside the dockerfile, perhaps with home directory set as /data.

Similarly the nextcloud example fails because `command: --secrets /var/lib/onionpipe/secrets.json app:80~80@nextcloud` https://github.com/cmars/onionpipe/blob/804fcbbcc08e62b6d512c26f6dfebdb435ac8fac/examples/nextcloud/docker-compose.yml#L12 tries to access `var/lib/onionpipe` but it does not have rights to do so. 

I am not sure how to best fix this. Volumes are only writable by root. Perhaps the volume should be under /data/.

There is also an issue of persistence here. Running `docker run onionpipe:latest --secrets /data/secrets.json 172.17.0.1:80~80@test` works (because user 1000 is allowed to write to /data/), but any subsequent run will use a new anonymous volume.

I think the best way here is to declare /data as a VOLUME in the dockerfile. 

Any other ideas? I will create a pull request.

**Comment by cmars** [comment]
VOLUME sounds good! I wonder if Docker buildkit features might support even more secure storage options for secrets but being able to run things seems like a good start.

Looking at this now, I wonder if there's a proper XDG package I could have used for the file location... might not have avoided this particular issue but could allow more flexibility in other contexts.
