### ISSUE TITLE
How to install (windows + linux)

### ISSUE THREAD

**Issue by wxnnvs** [cmars/onionpipe#27]
I might just be asking a stupid question but I cannot find it in the README

**Comment by cmars** [comment]
Added a section on installing binaries for Linux/Darwin in f6bf68eb7de374bfaf3fff336a29f2b84daf3d6f. These are built automatically by Github Actions when a new release tag is created. These will contain the latest Tor patch release when built; I try to trigger a build when Tor announces a security fix.

No guarantees it will work on all Linux systems though; there might be libc differences with older distros. Should work on Debian Bookworm. Darwin/macOS is also kind of experimental, I don't run macOS as a daily driver but Github seems to still build it.

Windows standalone binaries aren't supported yet, mostly because I don't have access to a Windows machine and I'm less familiar with the build toolchains on that platform. Windows should theoretically work fine with a `tor.exe` executable in your `%PATH%`. Your best bet there is to build from source.

**Comment by wxnnvs** [comment]
alright, thanks
windows seems to just not work as tor.exe seems to not work on PATH smh
thanks anyway

**Comment by cmars** [comment]
Might try playing with a VM when I get the chance. In the meantime, perhaps try Docker?

**Comment by wxnnvs** [comment]
true, but i won't use it probably as my audience seems to not need it, I like it tho

**Comment by Morsmalleo** [comment]
You should be able to run Onionpipe on Windows via the Windows Subsystem for Linux (WSL).

Try running through these steps below for installing WSL and also for installing Onionpipe on WSL, hopefully it helps out.

NOTE: I am not 100% positive if this will work, I haven't had time to test yet so I'm basing these steps off of other projects I've used on WSL that wouldn't normally work in a  Windows Environment.

<details>
<summary>01. Install WSL for Windows</summary>

# <div align="center">Installing WSL via PowerShell</div>

## <div align="center">Prerequisites</div>

- Windows 10 (Version 1903 or higher) or Windows 11.
- Administrator access on your Windows machine.

<br>

## <div align="center">Step 1: Open PowerShell</div>

- Press `Win + X` or right-click on the Start menu.
- Select **Windows PowerShell (Admin)** or **Windows Terminal (Admin)**.

<br>

## <div align="center">Step 2: Enable WSL:</div>

- Run the following command to enable WSL:

```powershell
wsl --install
```
This command will enable the required Windows features and install the default Linux distribution.

<br>

## <div align="center">Step 3: Restart Your Computer:</div>

- After the installation completes, you may be prompted to restart your computer. Do so to apply the changes.

<br>

## <div align="center">Step 4: Set Up Your Linux Distribution:</div>

- After your computer restarts, open PowerShell again.
- Launch your installed Linux distribution (the default is usually Ubuntu) by typing:

```powershell
wsl
```
- Follow the on-screen instructions to create a user account and set up your Linux environment.

<br>

## <div align="center">Step 5: Update Your Linux Distribution:</div>

Once your Linux distribution is set up, it's a good idea to update the package lists and upgrade the installed packages:

```bash
sudo apt update && sudo apt upgrade -y
```

<br>

Checking WSL Version:
- To verify your WSL version, use:

```powershell
wsl -l -v
```
This command will list the installed distributions and their WSL version.
</details>

<br>

<details>
<summary>02. Install Onionpipe on WSL</summary>


# Installing Onionpipe on WSL

## Prerequisites

1. **WSL Installed**: Ensure you have WSL installed on your Windows system. If not, you can follow the instructions from the official [Microsoft WSL Installation Guide](https://learn.microsoft.com/en-us/windows/wsl/install).

2. **Linux Distribution**: Have a Linux distribution installed and set up in WSL (e.g., Ubuntu).

3. **Updated System**: Ensure your WSL distribution is up to date:
```bash
sudo apt update && sudo apt upgrade -y
```

<br>

## <div align="center">Step 1: Install Dependencies</div>
Onionpipe requires some dependencies. Install them using the following commands:

```bash
sudo apt install -y curl apt-transport-https gnupg
```

<br>

## <div align="center">Step 2: Install Go</div>

Onionpipe is built using Go. So Install Go by running:

```bash
# Download the latest version of Go (1.21 as an example)
curl -OL https://golang.org/dl/go1.21.0.linux-amd64.tar.gz

# Extract and move Go to /usr/local
sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz

# Add Go to your PATH (add these lines to ~/.bashrc or ~/.zshrc)
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
source ~/.bashrc

# Verify installation
go version
```

<br>

## <div align="center">Step 3: Download and Install Onionpipe</div>
Clone the Onionpipe repository and install it:

```bash
# Clone the Onionpipe GitHub repository
git clone https://github.com/cmars/onionpipe.git

# Navigate to the Onionpipe directory
cd onionpipe

# Build Onionpipe
go build

# Install Onionpipe
sudo mv onionpipe /usr/local/bin/
```

<br>

## <div align="center">Step 4: Test Onionpipe Installation</div>
Verify that Onionpipe is installed correctly:

```bash
onionpipe
```
You should see some sort of output related to Onionpipe printed.
</details>

**Comment by wxnnvs** [comment]
Thanks
I've come to the the conclusion that i should buy a vps lol
